# docker-compose.yml

version: '3.8'
name: charcoal-live
services:
  charcoal_db:
    image: postgres:13.5
    container_name: charcoal-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=charcoal
      - POSTGRES_PASSWORD=admin
    volumes:
      - charcoal_db:/var/lib/postgresql/data
    ports:
      - 10000:5432
volumes:
  charcoal_db:
    driver: local
