# docker-compose.yml

version: '3.8'
name: charcoal-alpha
services:
  charcoal_db_alpha:
    image: postgres:13.5
    container_name: charcoal-db-alpha
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=charcoal
      - POSTGRES_PASSWORD=admin
    volumes:
      - charcoal_db_alpha:/var/lib/postgresql/data
    ports:
      - 10005:5432
volumes:
  charcoal_db_alpha:
    driver: local
