import { Navbar } from '@/components/Navbar';
import { classNames } from '@rain-cafe/react-utils';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import * as styles from './layout.module.scss';

const font = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={classNames(font.className, styles.body)}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
