name: Deploy

on:
  pull_request:
    branches:
      - main
      - alpha
  push:
    branches:
      - main
      - alpha

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Packages
        run: bun install --frozen-lockfile

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Packages
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Packages
        run: bun install --frozen-lockfile

      - name: Coverage
        run: bun test --coverage

      # TODO: Enable once LCOV is supported
      # https://github.com/oven-sh/bun/issues/4015
      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Packages
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build:next

  deploy:
    name: Deploy
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/alpha')
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'live' || github.ref_name }}
      url: ${{ github.ref_name == 'main' && 'https://charcoal.gg' || format('https://{0}--charcoal-gg.netlify.app', github.ref_name) }}
    needs: [lint, test, build]
    steps:
      - run: echo "Deployed to Netlify"
